# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPre_Processing = QtWidgets.QMenu(self.menubar)
        self.menuPre_Processing.setObjectName("menuPre_Processing")
        self.menuResult = QtWidgets.QMenu(self.menubar)
        self.menuResult.setObjectName("menuResult")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGrayscale = QtWidgets.QAction(MainWindow)
        self.actionGrayscale.setObjectName("actionGrayscale")
        self.actionCalculate_Gradient = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Gradient.setObjectName("actionCalculate_Gradient")
        self.actionBlur_Image = QtWidgets.QAction(MainWindow)
        self.actionBlur_Image.setObjectName("actionBlur_Image")
        self.actionBinary_Tresholding = QtWidgets.QAction(MainWindow)
        self.actionBinary_Tresholding.setObjectName("actionBinary_Tresholding")
        self.actionMorphology = QtWidgets.QAction(MainWindow)
        self.actionMorphology.setObjectName("actionMorphology")
        self.actionTresholding = QtWidgets.QAction(MainWindow)
        self.actionTresholding.setObjectName("actionTresholding")
        self.actionMorphology_2 = QtWidgets.QAction(MainWindow)
        self.actionMorphology_2.setObjectName("actionMorphology_2")
        self.actionBinary_Tresholding_2 = QtWidgets.QAction(MainWindow)
        self.actionBinary_Tresholding_2.setObjectName("actionBinary_Tresholding_2")
        self.actionMorphology_3 = QtWidgets.QAction(MainWindow)
        self.actionMorphology_3.setObjectName("actionMorphology_3")
        self.actionErode_and_Dilate = QtWidgets.QAction(MainWindow)
        self.actionErode_and_Dilate.setObjectName("actionErode_and_Dilate")
        self.actionFind_Contour = QtWidgets.QAction(MainWindow)
        self.actionFind_Contour.setObjectName("actionFind_Contour")
        self.actionDetect_Barcode = QtWidgets.QAction(MainWindow)
        self.actionDetect_Barcode.setObjectName("actionDetect_Barcode")
        self.menuPre_Processing.addAction(self.actionGrayscale)
        self.menuPre_Processing.addAction(self.actionCalculate_Gradient)
        self.menuPre_Processing.addAction(self.actionBlur_Image)
        self.menuPre_Processing.addAction(self.actionBinary_Tresholding_2)
        self.menuPre_Processing.addAction(self.actionMorphology_3)
        self.menuPre_Processing.addAction(self.actionErode_and_Dilate)
        self.menuResult.addAction(self.actionDetect_Barcode)
        self.menubar.addAction(self.menuPre_Processing.menuAction())
        self.menubar.addAction(self.menuResult.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuPre_Processing.setTitle(_translate("MainWindow", "Pre-Processing"))
        self.menuResult.setTitle(_translate("MainWindow", "Result"))
        self.actionGrayscale.setText(_translate("MainWindow", "Grayscale"))
        self.actionCalculate_Gradient.setText(_translate("MainWindow", "Calculate Gradient"))
        self.actionBlur_Image.setText(_translate("MainWindow", "Blur Image"))
        self.actionBinary_Tresholding.setText(_translate("MainWindow", "Binary Tresholding"))
        self.actionMorphology.setText(_translate("MainWindow", "Morphology"))
        self.actionTresholding.setText(_translate("MainWindow", "Tresholding"))
        self.actionMorphology_2.setText(_translate("MainWindow", "Morphology"))
        self.actionBinary_Tresholding_2.setText(_translate("MainWindow", "Binary Tresholding"))
        self.actionMorphology_3.setText(_translate("MainWindow", "Morphology"))
        self.actionErode_and_Dilate.setText(_translate("MainWindow", "Erode and Dilate "))
        self.actionFind_Contour.setText(_translate("MainWindow", "Find Contour"))
        self.actionDetect_Barcode.setText(_translate("MainWindow", "Detect Barcode"))
